fix(gitkraken): empty VERSION_PUBLISHED (fixes #1248)
wimpysworld/deb-get pull request #1249
Opened 2024-12-26 16:37 UTC by rasa

Since we are already using `sed`, I figure let's go all the way and *just* use `sed`.

I know it's cryptic as h*ll, but it works. :)

2024-12-26 16:46 UTC, rasa commented
Tested and working locally:
```bash
cd /etc/deb-get/99.local.d
wget https://raw.githubusercontent.com/rasa/deb-get/refs/heads/1248-fix-gitkraken/01-main/packages/gitkraken
deb-get update # optional
deb-get install gitkraken
```

2025-01-19 03:19 UTC, philclifford requested changes

2025-01-19 03:19 UTC, philclifford commented on 01-main/packages/gitkraken
> +    VERSION_PUBLISHED=$(sed -n -E "0,/.*name:\s*'([^']+)'/s//\1/p" "${CACHE_FILE}")
This results in a <CR> at the end of the published version,which upsets `dpkg --compare-versions` when you update.

``` shell
 deb-get show gitkraken| cat -v -
[...]
  [^[[32m+^[[0m] Including local package gitkraken
[...]  
GitKraken
  Package:	gitkraken
  Repository:	99-local
  Updater:	deb-get
  Installed:	10.6.1
  Published:	10.6.1^M
```

2025-01-19 07:38 UTC, rasa commented on 01-main/packages/gitkraken
> +    VERSION_PUBLISHED=$(sed -n -E "0,/.*name:\s*'([^']+)'/s//\1/p" "${CACHE_FILE}")
@philclifford Sorry, I'm not sure what, exactly, the error is. Is there a Ctrl-M at the end of the version?

I tested it, and it installed fine on Ubuntu 24.04, using the above command. I will retest.

2025-01-19 15:22 UTC, philclifford commented on 01-main/packages/gitkraken
> +    VERSION_PUBLISHED=$(sed -n -E "0,/.*name:\s*'([^']+)'/s//\1/p" "${CACHE_FILE}")
Yes, sorry to be unclear (at 4am ;-) ) - it is a Ctrl-M at the end of the version.  That only really affects update (because `dpkg --compare-versions` complains ) and probably upgrade (which will continually want to  upgrade because the compare "fails" ). Install will work fine as it just fetches the deb and installs it without comparing (except if the deb turns out to be the same version it'll skip the install )

2025-01-19 16:01 UTC, philclifford commented on 01-main/packages/gitkraken
> +    VERSION_PUBLISHED=$(sed -n -E "0,/.*name:\s*'([^']+)'/s//\1/p" "${CACHE_FILE}")
```suggestion
    VERSION_PUBLISHED=$(grep -E 'name:.*' $CACHE_FILE | grep -Eo  '([[:digit:]]+\.)+[[:digit:]]+' )
```
Not a single elegant `sed` but it works (for now) and is almost readable ...

2025-01-19 16:10 UTC, philclifford commented on 01-main/packages/gitkraken
> +    VERSION_PUBLISHED=$(sed -n -E "0,/.*name:\s*'([^']+)'/s//\1/p" "${CACHE_FILE}")
```suggestion
    VERSION_PUBLISHED=$(sed -n -E "s/.*name:.*'([0-9]+\.[0-9]+\.[0-9]+).*/\1/p" "$CACHE_FILE")
```
`sed` version which also works

2025-01-19 18:18 UTC, philclifford commented on 01-main/packages/gitkraken
> +    VERSION_PUBLISHED=$(sed -n -E "0,/.*name:\s*'([^']+)'/s//\1/p" "${CACHE_FILE}")
```suggestion
    VERSION_PUBLISHED=$(sed -n -E "s/.*name:\s*'([^']+)*'/\1/p" "$CACHE_FILE")
```
This appears to be working and does the elegant and correct thing.

2025-02-27 12:04 UTC, philclifford approved these changes

2025-03-16 23:51 UTC, philclifford approved these changes

2025-03-17 00:43 UTC, philclifford approved these changes

2025-04-15 07:57 UTC, merged