Added IVPN for Desktop
wimpysworld/deb-get pull request #414
Opened 2022-08-02 19:51 UTC by Xmetalfanx

Closes https://github.com/wimpysworld/deb-get/issues/44

2022-08-03 00:35 UTC, natanjunges requested changes

2022-08-03 00:35 UTC, natanjunges commented on deb-get
> +        URL=$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | cut -d'"' -f4)
This does not work, as the URL is in the body of the release.

2022-08-03 23:22 UTC, Xmetalfanx commented
I am taking this PR down .... not sure i like different options to get the URL since everything i try can get messed up if the maintainer puts things in a different order (say the two DEBs and RPMs in a different order than they are currently)

2022-08-03 23:22 UTC, closed without merging

2022-08-04 01:53 UTC, natanjunges commented
Analysing the download URLs, it seems that they have a fixed pattern where the only thing that changes is the version number, so you could just get the version information from the GitHub release and use it to define the `URL` variable.