Added MUCommander
wimpysworld/deb-get pull request #420
Opened 2022-08-02 23:59 UTC by Xmetalfanx

Closes https://github.com/wimpysworld/deb-get/issues/336

tested and installs and runs locally

2022-08-12 19:03 UTC, Xmetalfanx commented on deb-get
> +        URL="$(grep "browser_download_url.*${ARCHS_SUPPORTED}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
yes i did and updated (sure i made this mistake in another branch too) ... the logic makes so much more sense this way

2022-08-18 07:54 UTC, flexiondotorg requested changes
Please drop the Virtualbox change in README.md, rebase and squash the commits.

2022-09-10 20:31 UTC, Xmetalfanx commented
https://github.com/Xmetalfanx/deb-get/commit/5b8c8773ebadbb3af0996a2495aea01a6f39a929 not sure if github is showing the correct link above this comment after i changed what was asked and force-pushed after squashing the fix, but this link here is what i have now ... 

is this good, or is it better to close this PR (I will leave it open unles suggested otherwise) and make a new PR or just better to leave things "as-is"?

2022-10-28 16:06 UTC, natanjunges commented
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

2022-10-28 16:06 UTC, closed without merging