Added Firejail
wimpysworld/deb-get pull request #423
Opened 2022-08-03 00:10 UTC by Xmetalfanx

Closes https://github.com/wimpysworld/deb-get/issues/234

tested and it seems to work 

(I'd have to lookup how to actually use this but commands from the official firejail documentation work after the install)

2022-08-03 00:51 UTC, natanjunges requested changes

2022-08-03 00:51 UTC, natanjunges commented on deb-get
> +        URL="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
Multiple files are provided, depending on the architecture. The correct file should be selected based on `HOST_ARCH`, and the supported architectures should be listed in `ARCHS_SUPPORTED`. Read [CONTRIBUTING#creating-the-function](https://github.com/wimpysworld/deb-get/blob/main/CONTRIBUTING.md#creating-the-function) for further information.

2022-08-10 15:44 UTC, natanjunges requested changes

2022-08-10 15:44 UTC, natanjunges commented on deb-get
> +        URL="$(grep "browser_download_url.*${ARCHS_SUPPORTED}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
Did you mean `HOST_ARCH` instead of `ARCHS_SUPPORTED`?

2022-08-18 07:55 UTC, flexiondotorg requested changes
Please drop the Virtualbox change in README.md, rebase and squash the commits.

2022-10-28 16:06 UTC, natanjunges commented
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

2022-10-28 16:06 UTC, closed without merging