Added Eversticky
wimpysworld/deb-get pull request #424
Opened 2022-08-03 00:15 UTC by Xmetalfanx

Closes https://github.com/wimpysworld/deb-get/issues/230

Tested and works locally

2022-08-03 00:54 UTC, natanjunges requested changes

2022-08-03 00:54 UTC, natanjunges commented on deb-get
> +        VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8)"
This should have `tr -d v` at the end.

2022-08-03 17:33 UTC, Xmetalfanx commented
updated again ... so sorry about these issues ... I really should have checked some of the code i used that I assumed worked.   (was part of a bigger PR that addressed different issues all at once) ... that is one of the reasons i decided to do PR by PR in case some were ok but others had issues.

I am going back over my mistakes and will double check things before submitting PR's from now on

2022-08-03 19:36 UTC, natanjunges commented
No problem, just ensuring the quality of the PRs.

2022-08-18 07:55 UTC, flexiondotorg requested changes
Please drop the Virtualbox change in README.md, rebase and squash the commits.

2022-10-28 16:07 UTC, natanjunges commented
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

2022-10-28 16:07 UTC, closed without merging