allow AppimageLauncher to be installed in Debian
wimpysworld/deb-get pull request #521
Opened 2022-09-13 22:48 UTC by silentJET85

fixes #520 

This provides a way to install AppimageLauncher in Debian, while continuing to use the PPA in Ubuntu.

2022-09-14 00:48 UTC, natanjunges commented
A package should not have more than one installation method, since it would produce different outputs to `prettylist` in different systems. I think that in this case the best solution would be to replace the PPA with the GitHub releases method in all cases.

2022-09-19 09:03 UTC, flexiondotorg requested changes
Please consolidate this change so Ubuntu and Debian install via the same mechanism.

2022-09-20 00:30 UTC, silentJET85 commented
done

2022-09-21 22:50 UTC, flexiondotorg approved these changes

2022-09-21 22:50 UTC, merged