Add pomatez
wimpysworld/deb-get pull request #525
Opened 2022-09-17 05:08 UTC by takov751

Close #486

2022-09-19 08:53 UTC, flexiondotorg approved these changes

2022-09-19 09:01 UTC, flexiondotorg requested changes
Please rebase with `main`.

2022-09-19 12:13 UTC, takov751 commented
I still have to learn a few things about git , that's for sure

2022-10-28 16:14 UTC, natanjunges commented
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

2022-10-28 16:14 UTC, closed without merging