Add sunshine
wimpysworld/deb-get pull request #617
Opened 2022-10-28 21:06 UTC by ngilles

Adds support for `sunshine`, an nVidia gamestream host.

2022-11-03 15:58 UTC, natanjunges requested changes

2022-11-03 15:58 UTC, natanjunges commented on 01-main/README.md
> +| [<img src="../.github/github.png" align="top" width="20" />](https://docs.lizardbyte.dev/projects/sunshine/) | `sunshine` | <i>Sunshine is a Gamestream host for Moonlight.</i> |
This file is not meant to be changed by PRs.

2022-11-03 16:05 UTC, natanjunges requested changes

2022-11-20 19:28 UTC, flexiondotorg approved these changes

2022-11-20 19:29 UTC, merged