Add DeskCut
wimpysworld/deb-get pull request #618
Opened 2022-10-28 21:53 UTC by ngilles

Adds DeskCut 

Fixes #510 , supersedes #513

2022-11-03 15:57 UTC, natanjunges requested changes

2022-11-03 15:57 UTC, natanjunges commented on 01-main/README.md
> +| [<img src="../.github/github.png" align="top" width="20" />](https://github.com/NayamAmarshe/DeskCut) | `deskcut` | <i>An easy-to-use linux app that lets you create Desktop Shortcuts hassle-free</i
This file is not meant to be changed by PRs.

2022-11-03 16:05 UTC, natanjunges requested changes

2022-11-03 16:05 UTC, natanjunges commented on 01-main/packages/deskcut
> +ARCHS_SUPPORTED="amd64"
This is already the default, so not needed.

2022-11-20 19:29 UTC, flexiondotorg approved these changes

2022-11-20 19:29 UTC, merged