Add IPFS Desktop
wimpysworld/deb-get pull request #624
Opened 2022-10-30 12:05 UTC by mikabak

Requested here #623

2022-10-30 19:47 UTC, philclifford reviewed
LGTM

2022-11-03 16:01 UTC, natanjunges requested changes

2022-11-03 16:01 UTC, natanjunges commented on 01-main/packages/ipfs-desktop
> +ARCHS_SUPPORTED="amd64"
This is already the default, so not needed.

2022-11-22 02:31 UTC, philclifford requested changes
Please make the suggested updates to align with recent merges in `main`

2022-11-22 02:31 UTC, philclifford commented on 01-main/packages/ipfs-desktop
> +get_github_releases "https://api.github.com/repos/ipfs/ipfs-desktop/releases/latest"
Recent merges mean this should be changed to
```suggestion
get_github_releases "ipfs/ipfs-desktop" "latest"
```

2022-11-22 02:31 UTC, philclifford commented on 01-main/packages/ipfs-desktop
> +    URL="$(grep "browser_download_url.*\.deb\"" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
and also this one
```suggestion
    URL="$(grep "browser_download_url.*\.deb\"" "${CACHE_FILE}" | head -n1 | cut -d'"' -f4)"
```

2022-11-22 02:31 UTC, philclifford commented on 01-main/packages/ipfs-desktop
> +ARCHS_SUPPORTED="amd64"
```suggestion
```

2022-11-22 12:39 UTC, natanjunges approved these changes

2022-12-02 16:56 UTC, merged