Fix flameshot to use jammy release until kinetic is built
wimpysworld/deb-get pull request #627
Opened 2022-10-30 19:21 UTC by philclifford

Seems to work fine

![image](https://user-images.githubusercontent.com/8797027/198897431-b41c6be7-e34f-4798-b5d7-dcfba754abc3.png)

And also should now work on debian rather than breaking because the old pattern hard-coded 'ubuntu'

2022-10-30 19:33 UTC, philclifford commented on 01-main/packages/flameshot
> +    VERSION_PUBLISHED="${VERSION_TMP%%[-.]${UPSTREAM_ID}*}"
At least this needed to enable debian support

2022-11-17 14:13 UTC, natanjunges requested changes

2022-11-17 14:13 UTC, natanjunges commented on 01-main/packages/flameshot
> +DEFVER=3
This shouldn't be incremented.

2022-11-17 15:42 UTC, natanjunges approved these changes

2022-11-20 19:11 UTC, flexiondotorg approved these changes

2022-11-20 19:11 UTC, merged