Fix version and URL extraction
wimpysworld/deb-get pull request #628
Opened 2022-10-30 20:06 UTC by philclifford

More upstream twiddling handled

2022-11-17 14:15 UTC, natanjunges requested changes

2022-11-17 14:15 UTC, natanjunges commented on 01-main/packages/openrgb
> +DEFVER=2
This shouldn't be incremented.

2022-11-17 15:21 UTC, natanjunges approved these changes

2022-11-20 19:12 UTC, flexiondotorg requested changes
Please rebase with main

2022-11-21 13:11 UTC, flexiondotorg approved these changes

2022-11-21 13:11 UTC, merged