pick correct beersmith version for release
wimpysworld/deb-get pull request #633
Opened 2022-10-31 15:01 UTC by philclifford

They don't make it easy.

2022-10-31 21:30 UTC, philclifford commented
Still tries and fails to install on debian, in spite of restricting to ubuntu codenames :shrug: :crying_cat_face:

2022-11-17 14:15 UTC, natanjunges requested changes

2022-11-17 14:15 UTC, natanjunges commented on 01-main/packages/beersmith3
> +DEFVER=3
This shouldn't be incremented.

2022-11-20 19:13 UTC, flexiondotorg requested changes
Please rebase with main

2022-11-20 21:24 UTC, flexiondotorg approved these changes

2022-11-20 21:24 UTC, merged