RStudio Desktop fixed for move to posit.co
wimpysworld/deb-get pull request #640
Opened 2022-11-02 16:06 UTC by philclifford

Also updated to point debians at the recommended package.

closes #638

2022-11-17 14:16 UTC, natanjunges requested changes

2022-11-17 14:16 UTC, natanjunges commented on 01-main/packages/rstudio
> +DEFVER=2
This shouldn't be incremented.

2022-11-17 15:24 UTC, natanjunges approved these changes

2022-11-20 19:14 UTC, flexiondotorg requested changes
Please rebase with main

2022-11-20 19:36 UTC, philclifford commented
Need to re-sub

2022-11-20 19:36 UTC, closed without merging