Add Home Assistant supervised installer and os-agent
wimpysworld/deb-get pull request #642
Opened 2022-11-03 15:28 UTC by miGii

This adds:
[https://github.com/home-assistant/supervised-installer](url)
[https://github.com/home-assistant/os-agent](url)

2022-11-03 15:38 UTC, natanjunges requested changes

2022-11-03 16:19 UTC, miGii commented on 01-main/README.md
> +| [<img src="../.github/github.png" align="top" width="20" />](https://github.com/home-assistant/supervised-installer) | `supervised-installer` | <i>This is Home Assistant supervised installer, that
I can't seem to know how to read the contributing instructions. Fixed

2022-11-03 16:19 UTC, miGii commented on 01-main/packages/homeassistant-supervised
> +ARCHS_SUPPORTED="amd64"
Removed

2022-11-20 19:19 UTC, flexiondotorg approved these changes

2022-11-20 19:19 UTC, merged