Add Authy.
wimpysworld/deb-get pull request #791
Opened 2023-03-06 07:33 UTC by marosg42

Solves issue #790

2023-03-06 18:26 UTC, philclifford approved these changes

2023-03-23 19:06 UTC, philclifford commented
@marosg42 Oopsie - Pretty name and references here should say Authme not Authy (which is the Twilio one available via `snap` ) :confused: :bulb: .

2023-03-23 19:10 UTC, philclifford requested changes
And ideally change the PR title and commit comment too ;-)

2023-03-23 19:10 UTC, philclifford commented on 01-main/packages/authme
> +PRETTY_NAME="Authy"
PRETTY_NAME="Authme"

2023-03-24 21:59 UTC, marosg42 commented on 01-main/packages/authme
> +PRETTY_NAME="Authy"
oopsie indeed. Thanks.

2023-03-24 23:45 UTC, philclifford approved these changes
Thank you!

2023-04-26 09:51 UTC, merged