Add OpenTofu
wimpysworld/deb-get pull request #991
Opened 2024-02-07 08:47 UTC by felicianotech

Closes #880

Following the contrib guide, I didn't add the tool name to the list/manifest.

I've tested this with success on an Ubuntu 23.10 amd64 system.

2024-02-07 10:27 UTC, philclifford commented
You do need to add an entry to the 01-main.d/manifest. You just leave out changing the Readme list.

2024-02-08 16:27 UTC, philclifford requested changes
please add opentofu to the 01-main/manifest

2024-02-09 03:02 UTC, felicianotech commented
Updated

2024-02-09 14:29 UTC, philclifford approved these changes

2024-02-09 14:30 UTC, merged